version: 2

updates:

  # =========================
  # GitHub Actions
  # =========================
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # =========================
  # Docker
  # =========================
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"

  # =========================
  # rag_embedder
  # =========================
  - package-ecosystem: "uv"
    directory: "/rag_embedder"
    schedule:
      interval: "weekly"

    groups:
      rag-embedder-security-updates:
        applies-to: security-updates
        patterns:
          - "*"

  # =========================
  # rag_retriever
  # =========================
  - package-ecosystem: "uv"
    directory: "/rag_retriever"
    schedule:
      interval: "weekly"

    groups:
      rag-retriever-security-updates:
        applies-to: security-updates
        patterns:
          - "*"

  # =========================
  # rag_orchestrator
  # =========================
  - package-ecosystem: "uv"
    directory: "/rag_orchestrator"
    schedule:
      interval: "weekly"

    groups:
      rag-orchestrator-security-updates:
        applies-to: security-updates
        patterns:
          - "*"

  # =========================
  # rag_evaluator
  # =========================
  - package-ecosystem: "uv"
    directory: "/rag_evaluator"
    schedule:
      interval: "weekly"

    groups:
      rag-evaluator-security-updates:
        applies-to: security-updates
        patterns:
          - "*"

  # =========================
  # rag_ihm
  # =========================
  - package-ecosystem: "uv"
    directory: "/rag_ihm"
    schedule:
      interval: "weekly"

    groups:
      rag-ihm-security-updates:
        applies-to: security-updates
        patterns:
          - "*"

  # =========================
  # rag_mcp
  # =========================
  - package-ecosystem: "uv"
    directory: "/rag_mcp"
    schedule:
      interval: "weekly"

    groups:
      rag-mcp-security-updates:
        applies-to: security-updates
        patterns:
          - "*"