apiVersion: 1
groups:
    - orgId: 1
      name: Services up
      folder: RAG
      interval: 1m
      rules:
        - uid: efplid5wwhtkwa
          title: Embedder down
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: ffphcvbllh2ioa
              model:
                editorMode: code
                expr: up{job="rag_embedder"}
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: C
              queryType: expression
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                        type: eq
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: NoData
          execErrState: Error
          for: 1m
          annotations:
            description: |-
                L'endpoint /metrics du service rag_embedder n'est plus accessible.
                Vérifier l'état du conteneur Docker et les logs Loki associés.
            summary: Le service rag_embedder ne répond plus.
          isPaused: false
          notification_settings:
            receiver: Discord serveur RAG
