FROM python:3.12-slim

ENV UV_LINK_MODE=copy
ENV UV_PROJECT_ENVIRONMENT=/opt/venv
WORKDIR /app

RUN pip install --no-cache-dir uv

# deps du service (incluant dev -> mkdocs)
COPY pyproject.toml uv.lock* ./
ENV UV_HTTP_TIMEOUT=300
RUN uv sync --frozen

# doc uniquement
COPY mkdocs.yml ./
COPY docs ./docs

EXPOSE 8000
CMD ["uv", "run", "mkdocs", "serve", "-a", "0.0.0.0:8000"]
