FROM python:3.12-slim

ENV UV_LINK_MODE=copy
ENV UV_PROJECT_ENVIRONMENT=/opt/venv
WORKDIR /app

RUN pip install --no-cache-dir --only-binary :all: uv==0.9.8

# deps du service (incluant dev -> mkdocs)
COPY pyproject.toml uv.lock ./
ENV UV_HTTP_TIMEOUT=300
RUN uv sync --frozen

# doc uniquement
COPY mkdocs.yml ./
COPY docs ./docs

RUN useradd --create-home --uid 10001 appuser && chown -R appuser:appuser /app /opt/venv
USER appuser

EXPOSE 8000
CMD ["uv", "run", "--no-sync", "--no-build", "mkdocs", "serve", "-a", "0.0.0.0:8000"]
