global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "rag_embedder"
    metrics_path: "/metrics/"
    static_configs:
      - targets: ["rag_embedder:8000"]

  - job_name: "rag_reranker"
    metrics_path: "/metrics/"
    static_configs:
      - targets: ["rag_reranker:8000"]

  - job_name: "rag_orchestrator"
    metrics_path: "/metrics/"
    static_configs:
      - targets: ["rag_orchestrator:8000"]

  - job_name: "rag_retriever"
    metrics_path: "/metrics/"
    static_configs:
      - targets: ["rag_retriever:8000"]

  - job_name: "rag_evaluator"
    metrics_path: "/metrics/"
    static_configs:
      - targets: ["rag_evaluator:8000"]
