FROM python:3.12-slim

WORKDIR /app

RUN pip install --no-cache-dir \
    mkdocs==1.6.1 \
    mkdocs-material==9.7.1 \
    mkdocs-mermaid2-plugin==1.2.3

COPY mkdocs.yml ./
COPY docs ./docs

EXPOSE 8000
CMD ["mkdocs", "serve", "-a", "0.0.0.0:8000"]
